version: "3.1"

services:
    mysql:
        container_name: db
        image: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: dailygrow
            MYSQL_USER: dailygrow
            MYSQL_PASSWORD: dailygrow
        volumes:
            - ./my.cnf:/etc/mysql/my.cnf
    phpmyadmin:
        container_name: phpma
        image: phpmyadmin
        links:
            - mysql:db
        ports:
            - 8080:80
